/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica e devolve a situação consolidada da plataforma */
        get: operations["verificarSituacaoGeral"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saude/componente/{componente}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta a situação de um componente específico */
        get: operations["consultarComponente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Situação de um componente da plataforma */
        ComponenteDeSaudeResponse: {
            /**
             * @description Nome do componente monitorado
             * @example banco
             */
            componente?: string;
            /**
             * @description Situação atual do componente
             * @enum {string}
             */
            situacao?: "OPERANTE" | "DEGRADADO" | "INDISPONIVEL";
            /**
             * Format: date-time
             * @description Momento da última verificação
             */
            verificadoEm?: string;
            /** @description Verdadeiro quando o componente está operante e foi verificado há pouco */
            saudavel?: boolean;
        };
        /** @description Situação consolidada da plataforma */
        SaudeResponse: {
            /**
             * @description Pior situação entre os componentes
             * @enum {string}
             */
            situacaoGeral?: "OPERANTE" | "DEGRADADO" | "INDISPONIVEL";
            /**
             * @description Versão da aplicação
             * @example 0.1.0
             */
            versao?: string;
            /** @description Situação de cada componente monitorado */
            componentes?: components["schemas"]["ComponenteDeSaudeResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    verificarSituacaoGeral: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaudeResponse"];
                };
            };
        };
    };
    consultarComponente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                componente: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComponenteDeSaudeResponse"];
                };
            };
        };
    };
}
