/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/autenticacao/recuperacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envia um código de seis dígitos para o e-mail informado */
        post: operations["solicitarCodigo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/recuperacao/senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca a senha usando o código recebido por e-mail */
        post: operations["redefinirSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/recuperacao/codigo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confere o código antes de permitir a troca da senha */
        post: operations["validarCodigo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/entrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre uma sessão a partir de e-mail e senha */
        post: operations["entrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica e devolve a situação consolidada da plataforma */
        get: operations["verificarSituacaoGeral"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saude/falha-proposital": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Falha de propósito, para demonstrar as duas linhas de log de um erro */
        get: operations["falharDeProposito"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saude/componente/{componente}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta a situação de um componente específico */
        get: operations["consultarComponente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/sessao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devolve o usuário da sessão corrente */
        get: operations["consultarSessao"];
        put?: never;
        post?: never;
        /** Encerra a sessão corrente */
        delete: operations["sair"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Pedido de código de recuperação */
        SolicitarRecuperacaoRequest: {
            /**
             * @description E-mail cadastrado
             * @example leonardo@administraair.com.br
             */
            email?: string;
        };
        /** @description Redefinição de senha com o código recebido */
        RedefinirSenhaRequest: {
            /** @description E-mail cadastrado */
            email?: string;
            /**
             * @description Código de seis dígitos recebido por e-mail
             * @example 519274
             */
            codigo?: string;
            /** @description Senha nova, de no mínimo oito caracteres */
            novaSenha?: string;
        };
        /** @description Conferência do código de recuperação */
        ValidarCodigoRequest: {
            /** @description E-mail cadastrado */
            email?: string;
            /**
             * @description Código de seis dígitos recebido por e-mail
             * @example 519274
             */
            codigo?: string;
        };
        /** @description Credenciais de entrada */
        EntrarRequest: {
            /**
             * @description E-mail cadastrado
             * @example leonardo@administraair.com.br
             */
            email?: string;
            /** @description Senha da conta */
            senha?: string;
        };
        /** @description Usuário da sessão corrente */
        SessaoResponse: {
            /**
             * @description Nome de exibição
             * @example Leonardo Andrade
             */
            nome?: string;
            /**
             * @description E-mail cadastrado
             * @example leonardo@administraair.com.br
             */
            email?: string;
        };
        /** @description Situação de um componente da plataforma */
        ComponenteDeSaudeResponse: {
            /**
             * @description Nome do componente monitorado
             * @example banco
             */
            componente?: string;
            /**
             * @description Situação atual do componente
             * @enum {string}
             */
            situacao?: "OPERANTE" | "DEGRADADO" | "INDISPONIVEL";
            /**
             * Format: date-time
             * @description Momento da última verificação
             */
            verificadoEm?: string;
            /** @description Verdadeiro quando o componente está operante e foi verificado há pouco */
            saudavel?: boolean;
        };
        /** @description Situação consolidada da plataforma */
        SaudeResponse: {
            /**
             * @description Pior situação entre os componentes
             * @enum {string}
             */
            situacaoGeral?: "OPERANTE" | "DEGRADADO" | "INDISPONIVEL";
            /**
             * @description Versão da aplicação
             * @example 0.1.0
             */
            versao?: string;
            /** @description Situação de cada componente monitorado */
            componentes?: components["schemas"]["ComponenteDeSaudeResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    solicitarCodigo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitarRecuperacaoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redefinirSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedefinirSenhaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validarCodigo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidarCodigoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    entrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntrarRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessaoResponse"];
                };
            };
        };
    };
    verificarSituacaoGeral: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaudeResponse"];
                };
            };
        };
    };
    falharDeProposito: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    consultarComponente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                componente: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComponenteDeSaudeResponse"];
                };
            };
        };
    };
    consultarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                aether_sessao?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessaoResponse"];
                };
            };
        };
    };
    sair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                aether_sessao?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
