-- O diário de voos: cada linha é um TRECHO (uma perna voada). Trechos com o mesmo relatório de
-- voo formam o voo completo — todas as pernas voadas enquanto a aeronave esteve com o
-- proprietário. Cada trecho conta um pouso e alimenta o % de uso do rateio.

CREATE TABLE trecho (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id        BIGINT       NOT NULL REFERENCES aeronave (id),
    -- Identificador do voo, em monoespaçada na interface: "RV-2026-018". Livre porque cada
    -- operador numera do seu jeito; o agrupamento é por igualdade, não por formato.
    relatorio_de_voo   VARCHAR(20)  NOT NULL,
    numero_do_trecho   INTEGER      NOT NULL DEFAULT 1,
    data               DATE         NOT NULL,
    origem             VARCHAR(4)   NOT NULL,
    destino            VARCHAR(4)   NOT NULL,
    km                 NUMERIC(8,1) NOT NULL,
    partida_prevista   TIME,
    pouso_previsto     TIME,
    partida_realizada  TIME,
    pouso_realizado    TIME,
    -- Quem usou a aeronave neste trecho. Nulo = voo de manutenção, que o rateio divide entre
    -- todos os proprietários.
    proprietario_id    BIGINT       REFERENCES proprietario (id),
    observacoes        VARCHAR(500),
    criado_em          TIMESTAMPTZ  NOT NULL,
    atualizado_em      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT trecho_km_positivo CHECK (km > 0),
    CONSTRAINT trecho_origem_valida CHECK (origem ~ '^[A-Z]{4}$'),
    CONSTRAINT trecho_destino_valido CHECK (destino ~ '^[A-Z]{4}$'),
    CONSTRAINT trecho_numero_positivo CHECK (numero_do_trecho >= 1)
);

-- A tela recorta por aeronave e competência; é a consulta de todo carregamento da página.
CREATE INDEX trecho_por_aeronave_e_data ON trecho (aeronave_id, data);

COMMENT ON TABLE trecho IS 'Uma perna voada. Trechos com o mesmo relatório de voo formam o voo.';
COMMENT ON COLUMN trecho.proprietario_id IS 'Nulo = voo de manutenção, dividido entre todos.';
