-- Os lançamentos de custo: cada linha é uma despesa de uma aeronave, classificada em tipo
-- (fixo ou variável) e categoria, atribuída a um proprietário ou rateada entre todos.
--
-- O valor é sempre gravado em BRL. Lançamento em USD guarda o valor original e o câmbio do dia,
-- e o valor em BRL é derivado no ato — auditável para sempre, sem depender de cotação futura.

CREATE TABLE custo (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id      BIGINT        NOT NULL REFERENCES aeronave (id),
    tipo             VARCHAR(10)   NOT NULL,
    categoria        VARCHAR(30)   NOT NULL,
    data             DATE          NOT NULL,
    descricao        VARCHAR(200)  NOT NULL,
    -- Vínculo opcional com um relatório de voo: combustível e tarifas nascem de um voo.
    relatorio_de_voo VARCHAR(20),
    -- Nulo = rateado entre todos os proprietários, pela regra da aeronave.
    proprietario_id  BIGINT        REFERENCES proprietario (id),
    nota_fiscal      VARCHAR(40),
    moeda            VARCHAR(3)    NOT NULL DEFAULT 'BRL',
    valor_original   NUMERIC(14,2),
    cambio           NUMERIC(10,4),
    valor            NUMERIC(14,2) NOT NULL,
    criado_em        TIMESTAMPTZ   NOT NULL,
    atualizado_em    TIMESTAMPTZ   NOT NULL,
    CONSTRAINT custo_tipo_valido CHECK (tipo IN ('FIXO', 'VARIAVEL')),
    CONSTRAINT custo_moeda_valida CHECK (moeda IN ('BRL', 'USD')),
    CONSTRAINT custo_valor_positivo CHECK (valor > 0),
    -- USD sem câmbio não tem como virar BRL; BRL não carrega câmbio nenhum.
    CONSTRAINT custo_cambio_coerente CHECK (
        (moeda = 'BRL' AND valor_original IS NULL AND cambio IS NULL)
        OR (moeda <> 'BRL' AND valor_original > 0 AND cambio > 0)
    )
);

CREATE INDEX custo_por_aeronave_e_data ON custo (aeronave_id, data);

COMMENT ON TABLE custo IS 'Lançamento de despesa de uma aeronave, em BRL.';
COMMENT ON COLUMN custo.proprietario_id IS 'Nulo = rateado entre todos os proprietários.';
COMMENT ON COLUMN custo.cambio IS 'Cotação usada no dia do lançamento em moeda estrangeira.';
