-- A manutenção de cada aeronave, em duas peças:
--
-- 1. `manutencao` — os eventos: programados (aparecem no calendário de voos) e concluídos, que
--    formam o histórico permanente das intervenções.
-- 2. `parametro_de_controle` — os limites monitorados: "inspeção de célula a 3.600 h",
--    "troca a 3.000 ciclos", "CVA até 09/05/2027". O julgamento (quanto falta, se está próximo)
--    é derivado dos contadores da aeronave ou do calendário — nunca gravado.

CREATE TABLE manutencao (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id   BIGINT        NOT NULL REFERENCES aeronave (id),
    data          DATE          NOT NULL,
    hora          TIME,
    responsavel   VARCHAR(120),
    descricao     VARCHAR(200)  NOT NULL,
    valor         NUMERIC(14,2),
    status        VARCHAR(12)   NOT NULL,
    criado_em     TIMESTAMPTZ   NOT NULL,
    atualizado_em TIMESTAMPTZ   NOT NULL,
    CONSTRAINT manutencao_status_valido CHECK (status IN ('PROGRAMADA', 'CONCLUIDA')),
    CONSTRAINT manutencao_valor_positivo CHECK (valor IS NULL OR valor > 0)
);

CREATE INDEX manutencao_por_aeronave_e_data ON manutencao (aeronave_id, data);

CREATE TABLE parametro_de_controle (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id   BIGINT        NOT NULL REFERENCES aeronave (id),
    nome          VARCHAR(120)  NOT NULL,
    tipo          VARCHAR(10)   NOT NULL,
    -- Limite numérico para HORAS e CICLOS; data limite para DATA. Um dos dois, nunca ambos.
    limite        NUMERIC(10,1),
    data_limite   DATE,
    -- Faixa de atenção: a quantas horas/ciclos/dias do limite o parâmetro começa a avisar.
    aviso         NUMERIC(10,1) NOT NULL,
    criado_em     TIMESTAMPTZ   NOT NULL,
    atualizado_em TIMESTAMPTZ   NOT NULL,
    CONSTRAINT parametro_tipo_valido CHECK (tipo IN ('HORAS', 'CICLOS', 'DATA')),
    CONSTRAINT parametro_aviso_positivo CHECK (aviso > 0),
    CONSTRAINT parametro_limite_coerente CHECK (
        (tipo = 'DATA' AND data_limite IS NOT NULL AND limite IS NULL)
        OR (tipo <> 'DATA' AND limite IS NOT NULL AND data_limite IS NULL)
    )
);

COMMENT ON TABLE manutencao IS 'Evento de manutenção: programado ou concluído (histórico).';
COMMENT ON TABLE parametro_de_controle IS 'Limite monitorado; o quanto falta é derivado, nunca gravado.';
