-- As entradas de dinheiro no fundo de uma aeronave.
--
-- O aporte é o dinheiro que um proprietário transfere. Tem duas datas porque são duas perguntas:
-- `data` é quando o crédito caiu na conta; `competencia` é a que mês ele se refere — o aporte de
-- setembro pode chegar no dia 3 de outubro. A competência é gravada como o primeiro dia do mês.
--
-- O rendimento é o que a aplicação do saldo do fundo rendeu. É rateado pela participação, por
-- isso não tem proprietário; a competência dele é o mês da data do crédito.
--
-- Os dois são registrados só depois que o dinheiro existe: nenhuma data no futuro.

CREATE TABLE aporte (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id     BIGINT        NOT NULL REFERENCES aeronave (id),
    proprietario_id BIGINT        NOT NULL REFERENCES proprietario (id),
    data            DATE          NOT NULL,
    competencia     DATE          NOT NULL,
    valor           NUMERIC(14,2) NOT NULL,
    criado_em       TIMESTAMPTZ   NOT NULL,
    atualizado_em   TIMESTAMPTZ   NOT NULL,
    CONSTRAINT aporte_valor_positivo CHECK (valor > 0),
    CONSTRAINT aporte_competencia_no_primeiro_dia CHECK (EXTRACT(DAY FROM competencia) = 1)
);

CREATE INDEX aporte_por_aeronave_e_competencia ON aporte (aeronave_id, competencia);

CREATE TABLE rendimento (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id    BIGINT        NOT NULL REFERENCES aeronave (id),
    data           DATE          NOT NULL,
    aplicacao      VARCHAR(60)   NOT NULL,
    -- O saldo aplicado e a taxa são o extrato do banco: opcionais, e nunca recalculam o valor.
    saldo_aplicado NUMERIC(14,2),
    taxa           NUMERIC(7,4),
    valor          NUMERIC(14,2) NOT NULL,
    criado_em      TIMESTAMPTZ   NOT NULL,
    atualizado_em  TIMESTAMPTZ   NOT NULL,
    CONSTRAINT rendimento_valor_positivo CHECK (valor > 0),
    CONSTRAINT rendimento_saldo_positivo CHECK (saldo_aplicado IS NULL OR saldo_aplicado > 0),
    CONSTRAINT rendimento_taxa_positiva CHECK (taxa IS NULL OR taxa > 0)
);

CREATE INDEX rendimento_por_aeronave_e_data ON rendimento (aeronave_id, data);

COMMENT ON TABLE aporte IS 'Dinheiro de um proprietário no fundo de uma aeronave.';
COMMENT ON COLUMN aporte.data IS 'Quando o crédito caiu na conta.';
COMMENT ON COLUMN aporte.competencia IS 'Mês a que o aporte se refere, gravado no dia 1.';
COMMENT ON TABLE rendimento IS 'O que a aplicação do saldo do fundo rendeu; rateado pela participação.';
COMMENT ON COLUMN rendimento.taxa IS 'Taxa do mês em %, como no extrato.';
