-- As trocas de KM: horas que um proprietário cede a outro na mesma aeronave, a devolver depois.
--
-- É controle entre proprietários, não lançamento: o rateio do fechamento não muda — o custo
-- continua com quem voou. O R$/hora é o valor combinado para acertar em dinheiro, se a
-- devolução não vier em horas. Concluir registra a devolução; reabrir existe para o engano.

CREATE TABLE troca_de_km (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id      BIGINT        NOT NULL REFERENCES aeronave (id),
    data             DATE          NOT NULL,
    cedente_id       BIGINT        NOT NULL REFERENCES proprietario (id),
    recebedor_id     BIGINT        NOT NULL REFERENCES proprietario (id),
    horas            NUMERIC(6,1)  NOT NULL,
    km               NUMERIC(10,1),
    valor_por_hora   NUMERIC(12,2),
    relatorio_de_voo VARCHAR(20),
    observacao       VARCHAR(300),
    situacao         VARCHAR(10)   NOT NULL DEFAULT 'PENDENTE',
    concluida_em     DATE,
    criado_em        TIMESTAMPTZ   NOT NULL,
    atualizado_em    TIMESTAMPTZ   NOT NULL,
    CONSTRAINT troca_entre_proprietarios_diferentes CHECK (cedente_id <> recebedor_id),
    CONSTRAINT troca_horas_positivas CHECK (horas > 0),
    CONSTRAINT troca_km_nao_negativo CHECK (km IS NULL OR km >= 0),
    CONSTRAINT troca_valor_positivo CHECK (valor_por_hora IS NULL OR valor_por_hora > 0),
    CONSTRAINT troca_situacao_valida CHECK (situacao IN ('PENDENTE', 'CONCLUIDA')),
    -- Concluída tem data de devolução; pendente não tem.
    CONSTRAINT troca_conclusao_coerente CHECK (
        (situacao = 'PENDENTE' AND concluida_em IS NULL)
        OR (situacao = 'CONCLUIDA' AND concluida_em IS NOT NULL)
    )
);

CREATE INDEX troca_por_situacao_e_data ON troca_de_km (situacao, data);

COMMENT ON TABLE troca_de_km IS 'Horas cedidas entre proprietários de uma aeronave, a devolver.';
COMMENT ON COLUMN troca_de_km.valor_por_hora IS 'Valor combinado para acerto em dinheiro, se houver.';
