-- Os documentos anexados a uma aeronave: contrato, apólice, CVA digitalizado, laudos.
--
-- O banco guarda só o que se lista e se busca; o conteúdo fica no armazenamento de arquivos,
-- endereçado pela `chave` — um UUID, nunca o nome que o usuário deu ao arquivo. Trocar o disco do
-- servidor por um bucket é copiar os arquivos e trocar o adaptador (ADR-0020).
--
-- Não confundir com o documento regulatório com vencimento (CVA, RETA), que é um atributo da
-- aeronave e não um arquivo.

CREATE TABLE documento (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id       BIGINT        NOT NULL REFERENCES aeronave (id),
    nome              VARCHAR(200)  NOT NULL,
    tipo_de_conteudo  VARCHAR(120)  NOT NULL,
    tamanho           BIGINT        NOT NULL,
    chave             VARCHAR(80)   NOT NULL UNIQUE,
    enviado_por       VARCHAR(120)  NOT NULL,
    criado_em         TIMESTAMPTZ   NOT NULL,
    CONSTRAINT documento_tamanho_positivo CHECK (tamanho > 0)
);

CREATE INDEX documento_por_aeronave ON documento (aeronave_id, criado_em);

COMMENT ON TABLE documento IS 'Arquivo anexado a uma aeronave; o conteúdo fica no armazenamento.';
COMMENT ON COLUMN documento.chave IS 'Endereço do conteúdo no armazenamento: UUID, nunca o nome do arquivo.';
