-- Os avisos da Central são derivados — vencimentos, limites de manutenção, validades da
-- tripulação, fundo descoberto — e nunca gravados. O que se grava é só quem já leu qual.
--
-- A chave do aviso inclui o prazo (RETA:3:2027-07-09): renovar o documento gera aviso novo, que
-- nasce não lido, em vez de herdar a leitura do anterior.

CREATE TABLE aviso_lido (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL REFERENCES usuario (id),
    chave       VARCHAR(120) NOT NULL,
    lido_em     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT aviso_lido_uma_vez UNIQUE (usuario_id, chave)
);

COMMENT ON TABLE aviso_lido IS 'Quem leu qual aviso; os avisos em si são derivados, nunca gravados.';
