-- Feature de exemplo do bootstrap: situação operacional da própria plataforma.
CREATE TABLE registro_de_saude (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    componente    VARCHAR(60) NOT NULL,
    situacao      VARCHAR(20) NOT NULL,
    verificado_em TIMESTAMPTZ NOT NULL,
    CONSTRAINT registro_de_saude_componente_unico UNIQUE (componente),
    CONSTRAINT registro_de_saude_situacao_valida
        CHECK (situacao IN ('OPERANTE', 'DEGRADADO', 'INDISPONIVEL'))
);

COMMENT ON TABLE registro_de_saude IS 'Situação conhecida de cada componente monitorado da plataforma.';

-- Componentes monitorados desde o primeiro deploy. A situação real é reescrita a cada verificação.
INSERT INTO registro_de_saude (componente, situacao, verificado_em) VALUES
    ('api',   'OPERANTE', NOW()),
    ('banco', 'OPERANTE', NOW());
