-- Quem entra no Aether e por quais meios. Três tabelas com ciclos de vida distintos:
-- o usuário é permanente, o código de recuperação vive minutos, a sessão vive horas.

CREATE TABLE usuario (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120) NOT NULL,
    -- Guardado sempre em minúsculas: é a chave de entrada e não pode depender de como foi digitado.
    email         VARCHAR(180) NOT NULL,
    -- Hash BCrypt. Nulo enquanto o usuário não definiu a própria senha.
    senha         VARCHAR(100),
    situacao      VARCHAR(20)  NOT NULL,
    tentativas    INTEGER      NOT NULL DEFAULT 0,
    bloqueado_ate TIMESTAMPTZ,
    criado_em     TIMESTAMPTZ  NOT NULL,
    atualizado_em TIMESTAMPTZ  NOT NULL,
    CONSTRAINT usuario_email_unico UNIQUE (email),
    CONSTRAINT usuario_situacao_valida
        CHECK (situacao IN ('ATIVO', 'PENDENTE', 'INATIVO')),
    -- A regra "administrador não define senha de ninguém" tem um corolário verificável: um usuário
    -- só chega a ATIVO depois de ele mesmo criar a senha.
    CONSTRAINT usuario_ativo_possui_senha
        CHECK (situacao <> 'ATIVO' OR senha IS NOT NULL),
    CONSTRAINT usuario_tentativas_nao_negativas
        CHECK (tentativas >= 0)
);

COMMENT ON TABLE usuario IS 'Pessoa com acesso ao Aether.';
COMMENT ON COLUMN usuario.senha IS 'Hash BCrypt da senha; nulo enquanto o convite não foi concluído.';

CREATE TABLE codigo_de_recuperacao (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT       NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    -- Hash BCrypt do código. Seis dígitos são pouca entropia: o que protege é o hash lento
    -- somado ao limite de tentativas e à validade curta, não o segredo em si.
    codigo     VARCHAR(100) NOT NULL,
    expira_em  TIMESTAMPTZ  NOT NULL,
    usado_em   TIMESTAMPTZ,
    tentativas INTEGER      NOT NULL DEFAULT 0,
    criado_em  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT codigo_de_recuperacao_tentativas_nao_negativas
        CHECK (tentativas >= 0)
);

COMMENT ON TABLE codigo_de_recuperacao IS 'Código de seis dígitos enviado por e-mail para redefinir a senha.';

-- A consulta é sempre "o código vigente deste usuário": índice descendente por criação.
CREATE INDEX codigo_de_recuperacao_por_usuario
    ON codigo_de_recuperacao (usuario_id, criado_em DESC);

CREATE TABLE sessao_de_acesso (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT       NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    -- SHA-256 do token sorteado. Aqui basta hash rápido: o token tem 256 bits de entropia,
    -- então não há dicionário a percorrer — o hash existe para que vazar a tabela não dê sessão.
    token        VARCHAR(100) NOT NULL,
    expira_em    TIMESTAMPTZ  NOT NULL,
    encerrada_em TIMESTAMPTZ,
    criado_em    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT sessao_de_acesso_token_unico UNIQUE (token)
);

COMMENT ON TABLE sessao_de_acesso IS 'Sessão aberta por um usuário; o cookie carrega o token em claro.';
