-- A primeira tela restrita do Aether é Usuários, e ela exige três coisas que o V2 não previa:
-- saber o que cada pessoa é (papel), quando ela esteve aqui pela última vez, e por onde passa o
-- convite de quem ainda não criou senha.

ALTER TABLE usuario
    -- O DEFAULT preenche as linhas já gravadas, e fica. A intenção era removê-lo em seguida — papel
    -- é decisão de quem convida, não valor que o banco escolha sozinho —, mas o seed de
    -- desenvolvimento (V900) insere sem a coluna e é migration já aplicada, que não se edita. Como
    -- ele roda depois desta, sem o DEFAULT o ambiente local não sobe.
    -- Na prática o valor nunca é usado: a entidade sempre grava o papel, e GESTOR é o papel de
    -- menor alcance entre os quatro — errar para baixo, se algum dia for usado.
    ADD COLUMN papel VARCHAR(20) NOT NULL DEFAULT 'GESTOR',
    ADD COLUMN ultimo_acesso TIMESTAMPTZ;

ALTER TABLE usuario
    ADD CONSTRAINT usuario_papel_valido
        CHECK (papel IN ('ADMINISTRADOR', 'GESTOR', 'PROPRIETARIO', 'PILOTO'));

COMMENT ON COLUMN usuario.papel IS 'O que a pessoa é no Aether; ADMINISTRADOR é quem administra usuários.';
COMMENT ON COLUMN usuario.ultimo_acesso IS 'Instante da última entrada bem-sucedida; nulo para quem nunca entrou.';

-- A tela de Usuários filtra por papel e por situação, e ordena por nome. Um índice por papel
-- sozinho não paga: a tabela é pequena (dezenas de linhas por inquilino) e o filtro combina três
-- critérios. Entra quando o volume justificar, medido.

CREATE TABLE convite (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT       NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    -- SHA-256 do token sorteado, como em sessao_de_acesso e pelo mesmo motivo: 256 bits de
    -- entropia não têm dicionário a percorrer, e o resumo existe para que vazar a tabela não
    -- entregue convites abertos. O código de recuperação é BCrypt porque tem seis dígitos.
    token      VARCHAR(100) NOT NULL,
    expira_em  TIMESTAMPTZ  NOT NULL,
    usado_em   TIMESTAMPTZ,
    criado_em  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT convite_token_unico UNIQUE (token)
);

COMMENT ON TABLE convite IS 'Link de uso único pelo qual a pessoa convidada cria a própria senha.';

-- A consulta é sempre "o convite vigente deste usuário": índice descendente por criação.
CREATE INDEX convite_por_usuario ON convite (usuario_id, criado_em DESC);
