-- A aeronave: o objeto central do Aether. Esta migration cria só o cadastro e a camada
-- regulatória que a tela de Aeronaves consome — matrícula, modelo, base e os dois vencimentos que
-- decidem se ela pode voar.
--
-- O que NÃO está aqui, e é de propósito: contadores de horas e ciclos (TAH/TAC), participações de
-- proprietários, saldo de fundo e custo. Cada um pertence a uma feature que ainda não existe, e a
-- coluna correspondente da tela fica de fora até lá.

CREATE TABLE aeronave (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Matrícula do RAB, sempre em maiúsculas. É a identidade pública da aeronave: o produto
    -- inteiro a exibe em monoespaçada, e é por ela que as pessoas se referem ao equipamento.
    matricula       VARCHAR(10)  NOT NULL,
    modelo          VARCHAR(120) NOT NULL,
    -- Aeródromo onde a aeronave fica normalmente, em código ICAO de quatro letras (SBSP).
    base            VARCHAR(4)   NOT NULL,
    -- Certificado de Verificação de Aeronavegabilidade. Validade de 12 meses no RBAC 91.
    vencimento_cva  DATE         NOT NULL,
    -- Seguro obrigatório de Responsabilidade do Explorador ou Transportador Aéreo.
    vencimento_reta DATE         NOT NULL,
    criado_em       TIMESTAMPTZ  NOT NULL,
    atualizado_em   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT aeronave_matricula_unica UNIQUE (matricula),
    -- Prefixo brasileiro do RAB: PP, PR, PS, PT ou PU, hífen e três letras.
    CONSTRAINT aeronave_matricula_valida
        CHECK (matricula ~ '^P[PRSTU]-[A-Z]{3}$'),
    CONSTRAINT aeronave_base_valida
        CHECK (base ~ '^[A-Z]{4}$')
);

COMMENT ON TABLE aeronave IS 'Jato ou helicóptero sob gestão no Aether.';
COMMENT ON COLUMN aeronave.matricula IS 'Matrícula do RAB, maiúscula: PS-MEP.';
COMMENT ON COLUMN aeronave.vencimento_cva IS 'Vencimento do Certificado de Verificação de Aeronavegabilidade.';
COMMENT ON COLUMN aeronave.vencimento_reta IS 'Vencimento da apólice RETA.';

-- A tela ordena por matrícula, e a frota do primeiro cliente tem 30 linhas. Índice nenhum além do
-- único da matrícula se justifica ainda.
