-- O proprietário: pessoa física ou jurídica titular de participação em aeronaves. Esta migration
-- cria só o cadastro — identificação, contato e a cor que o identifica na interface.
--
-- O que NÃO está aqui, e é de propósito: participações (percentual por aeronave), saldo de fundo
-- e histórico de contratos. Cada um pertence à feature de detalhe da aeronave, que ainda não
-- existe — as colunas correspondentes da tela mostram "sem vínculo" até lá.

CREATE TABLE proprietario (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                 VARCHAR(120) NOT NULL,
    -- CPF (11 dígitos) ou CNPJ (14), gravado só com dígitos. Opcional: o cadastro pode nascer
    -- antes do documento chegar — o contrato de participação é que vai exigi-lo.
    cpf_cnpj             VARCHAR(14),
    email                VARCHAR(180),
    telefone             VARCHAR(20),
    -- Cor com que os trechos deste proprietário aparecem no calendário e nas grades.
    cor_de_identificacao VARCHAR(20)  NOT NULL,
    situacao             VARCHAR(10)  NOT NULL,
    criado_em            TIMESTAMPTZ  NOT NULL,
    atualizado_em        TIMESTAMPTZ  NOT NULL,
    CONSTRAINT proprietario_cpf_cnpj_unico UNIQUE (cpf_cnpj),
    CONSTRAINT proprietario_cpf_cnpj_valido
        CHECK (cpf_cnpj IS NULL OR cpf_cnpj ~ '^[0-9]{11}$' OR cpf_cnpj ~ '^[0-9]{14}$'),
    CONSTRAINT proprietario_situacao_valida
        CHECK (situacao IN ('ATIVO', 'INATIVO'))
);

COMMENT ON TABLE proprietario IS 'Pessoa física ou jurídica titular de participação em aeronaves.';
COMMENT ON COLUMN proprietario.cpf_cnpj IS 'Só dígitos: 11 para CPF, 14 para CNPJ.';
COMMENT ON COLUMN proprietario.cor_de_identificacao IS 'Cor de identificação na interface, de uma paleta fixa.';

-- A tela ordena por nome e o primeiro cliente tem poucas dezenas de proprietários. Nenhum índice
-- além do único do documento se justifica ainda.
