-- O contrato de participação: quem é dono de quanto de cada aeronave, de um instante até o
-- próximo contrato. Contrato não se edita — se arquiva: alterar participações cria um novo e
-- encerra o vigente (fim_da_vigencia). É esse histórico que o rateio de competências passadas
-- vai consultar.

CREATE TABLE contrato_de_participacao (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id        BIGINT       NOT NULL REFERENCES aeronave (id),
    inicio_da_vigencia TIMESTAMPTZ  NOT NULL,
    fim_da_vigencia    TIMESTAMPTZ,
    -- Nome de quem salvou, gravado no ato: o histórico mostra "alterado por" para sempre,
    -- mesmo que o usuário mude de nome ou saia.
    criado_por         VARCHAR(120) NOT NULL,
    CONSTRAINT contrato_vigencia_coerente
        CHECK (fim_da_vigencia IS NULL OR fim_da_vigencia >= inicio_da_vigencia)
);

-- No máximo UM contrato vigente por aeronave: é o índice parcial que transforma a convenção
-- "vigente = fim nulo" em regra que o banco defende.
CREATE UNIQUE INDEX contrato_vigente_unico
    ON contrato_de_participacao (aeronave_id)
    WHERE fim_da_vigencia IS NULL;

CREATE TABLE participacao (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_id     BIGINT        NOT NULL REFERENCES contrato_de_participacao (id),
    proprietario_id BIGINT        NOT NULL REFERENCES proprietario (id),
    -- De 0,01 a 100,00: participação zerada não é participação, é ausência.
    percentual      NUMERIC(5,2)  NOT NULL,
    CONSTRAINT participacao_percentual_valido
        CHECK (percentual > 0 AND percentual <= 100),
    CONSTRAINT participacao_unica_por_contrato UNIQUE (contrato_id, proprietario_id)
);

COMMENT ON TABLE contrato_de_participacao IS 'Foto das participações de uma aeronave num período de vigência.';
COMMENT ON COLUMN participacao.percentual IS 'Percentual de propriedade, duas casas. A soma do contrato fecha em 100.';
