-- A tripulação vinculada a cada aeronave: pilotos com as validades que decidem se podem voar
-- (CMA — Certificado Médico Aeronáutico — e CHT — Certificado de Habilitação Técnica).
--
-- O vínculo é direto com a aeronave, como no protótipo: o produto gerencia a tripulação DE uma
-- aeronave, não um cadastro global de pilotos. Se um dia a mesma pessoa servir a duas aeronaves,
-- a promoção para cadastro global é uma migration — hoje seria só indireção.

CREATE TABLE tripulante (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aeronave_id   BIGINT        NOT NULL REFERENCES aeronave (id),
    nome          VARCHAR(120)  NOT NULL,
    -- Código ANAC do tripulante, só dígitos. Opcional: o cadastro pode nascer antes do papel.
    canac         VARCHAR(10),
    funcao        VARCHAR(12)   NOT NULL,
    validade_cma  DATE,
    validade_cht  DATE,
    horas_totais  NUMERIC(10,1),
    telefone      VARCHAR(20),
    email         VARCHAR(180),
    situacao      VARCHAR(10)   NOT NULL,
    criado_em     TIMESTAMPTZ   NOT NULL,
    atualizado_em TIMESTAMPTZ   NOT NULL,
    CONSTRAINT tripulante_funcao_valida
        CHECK (funcao IN ('COMANDANTE', 'COPILOTO', 'INSTRUTOR', 'EXAMINADOR')),
    CONSTRAINT tripulante_situacao_valida
        CHECK (situacao IN ('ATIVO', 'INATIVO')),
    CONSTRAINT tripulante_horas_nao_negativas
        CHECK (horas_totais IS NULL OR horas_totais >= 0)
);

COMMENT ON TABLE tripulante IS 'Piloto vinculado a uma aeronave, com validades de CMA e CHT.';
COMMENT ON COLUMN tripulante.canac IS 'Código ANAC, só dígitos.';
